"""phase 2 core domain models"""

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'dbc5b8693c76'
down_revision = '0001_phase1_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='document_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('source_uri', name=op.f('uq_knowledge_documents_source_uri'))
    )
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('regions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crop_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_table('embedded_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=768), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_embedded_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedded_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_embedded_chunks_document_chunk')
    )
    op.create_index(op.f('ix_embedded_chunks_document_id'), 'embedded_chunks', ['document_id'], unique=False)
    op.create_table('sensor_stations',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', name='station_status'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('station_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_sensor_stations_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_stations'))
    )
    op.create_index(op.f('ix_sensor_stations_code'), 'sensor_stations', ['code'], unique=True)
    op.create_index(op.f('ix_sensor_stations_region_id'), 'sensor_stations', ['region_id'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wind_speed_mps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=True),
    sa.Column('tide_level_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('condition_summary', sa.String(length=255), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_weather_snapshots_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_snapshots'))
    )
    op.create_index(op.f('ix_weather_snapshots_observed_at'), 'weather_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_region_id'), 'weather_snapshots', ['region_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('salinity_dsm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('water_level_m', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_level_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['sensor_stations.id'], name=op.f('fk_sensor_readings_station_id_sensor_stations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings'))
    )
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_station_id'), 'sensor_readings', ['station_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('based_on_reading_id', sa.UUID(), nullable=True),
    sa.Column('based_on_weather_id', sa.UUID(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.Enum('safe', 'warning', 'danger', 'critical', name='risk_level'), nullable=False),
    sa.Column('salinity_dsm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('trend_direction', sa.Enum('rising', 'falling', 'stable', 'unknown', name='trend_direction'), nullable=False),
    sa.Column('trend_delta_dsm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['based_on_reading_id'], ['sensor_readings.id'], name=op.f('fk_risk_assessments_based_on_reading_id_sensor_readings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['based_on_weather_id'], ['weather_snapshots.id'], name=op.f('fk_risk_assessments_based_on_weather_id_weather_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_risk_assessments_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['sensor_stations.id'], name=op.f('fk_risk_assessments_station_id_sensor_stations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_assessed_at'), 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_region_id'), 'risk_assessments', ['region_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_station_id'), 'risk_assessments', ['station_id'], unique=False)
    op.create_table('action_plans',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'simulated', 'closed', name='action_plan_status'), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_action_plans_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], name=op.f('fk_action_plans_risk_assessment_id_risk_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_plans'))
    )
    op.create_index(op.f('ix_action_plans_region_id'), 'action_plans', ['region_id'], unique=False)
    op.create_index(op.f('ix_action_plans_risk_assessment_id'), 'action_plans', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_action_plans_status'), 'action_plans', ['status'], unique=False)
    op.create_table('alert_events',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('safe', 'warning', 'danger', 'critical', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alert_status'), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_alert_events_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], name=op.f('fk_alert_events_risk_assessment_id_risk_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_region_id'), 'alert_events', ['region_id'], unique=False)
    op.create_index(op.f('ix_alert_events_risk_assessment_id'), 'alert_events', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_alert_events_severity'), 'alert_events', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_events_triggered_at'), 'alert_events', ['triggered_at'], unique=False)
    op.create_table('action_executions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('notify-farmers', 'wait-safe-window', 'close-gate-simulated', 'start-pump-simulated', name='action_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], name=op.f('fk_action_executions_plan_id_action_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_action_executions_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_executions'))
    )
    op.create_index(op.f('ix_action_executions_plan_id'), 'action_executions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_action_executions_region_id'), 'action_executions', ['region_id'], unique=False)
    op.create_index(op.f('ix_action_executions_status'), 'action_executions', ['status'], unique=False)
    op.create_table('decision_logs',
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=True),
    sa.Column('action_plan_id', sa.UUID(), nullable=True),
    sa.Column('action_execution_id', sa.UUID(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'operator', 'agent', name='decision_actor_type'), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('store_as_memory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_execution_id'], ['action_executions.id'], name=op.f('fk_decision_logs_action_execution_id_action_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], name=op.f('fk_decision_logs_action_plan_id_action_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_decision_logs_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], name=op.f('fk_decision_logs_risk_assessment_id_risk_assessments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_logs'))
    )
    op.create_index(op.f('ix_decision_logs_logged_at'), 'decision_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_decision_logs_region_id'), 'decision_logs', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_region_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_logged_at'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index(op.f('ix_action_executions_status'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_region_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_plan_id'), table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_alert_events_triggered_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_severity'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_risk_assessment_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_region_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_action_plans_status'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_risk_assessment_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_region_id'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_risk_assessments_station_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_region_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessed_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_sensor_readings_station_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_weather_snapshots_region_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_observed_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_sensor_stations_region_id'), table_name='sensor_stations')
    op.drop_index(op.f('ix_sensor_stations_code'), table_name='sensor_stations')
    op.drop_table('sensor_stations')
    op.drop_index(op.f('ix_embedded_chunks_document_id'), table_name='embedded_chunks')
    op.drop_table('embedded_chunks')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.execute("DROP TYPE IF EXISTS decision_actor_type")
    op.execute("DROP TYPE IF EXISTS execution_status")
    op.execute("DROP TYPE IF EXISTS action_type")
    op.execute("DROP TYPE IF EXISTS alert_status")
    op.execute("DROP TYPE IF EXISTS alert_severity")
    op.execute("DROP TYPE IF EXISTS action_plan_status")
    op.execute("DROP TYPE IF EXISTS trend_direction")
    op.execute("DROP TYPE IF EXISTS risk_level")
    op.execute("DROP TYPE IF EXISTS station_status")
    op.execute("DROP TYPE IF EXISTS document_status")
    # ### end Alembic commands ###

